import { ThemeRegistry, type PrintTheme, type PrintRenderContext } from './theme-registry';

// jspdf-autotable - typed loosely to avoid pulling its types into the public surface.

// eslint-disable-next-line @typescript-eslint/no-require-imports
const autoTable: any = require('jspdf-autotable').default ?? require('jspdf-autotable');

/**
 * Classic theme — traditional Indian invoice layout with boxed header, bordered
 * items table, and signature block bottom-right. Every system label is sourced
 * via ctx.t(...) so the same render path drives en/gu/hi PDFs.
 *
 * Free text (party name, item name, address, GSTIN) prints as-is per D-39.
 * When invoice.eInvoice.irn is present, the IRP signed QR (ctx.irpQrBase64)
 * is rendered per CGST Rule 48. The QR is pre-generated by PrintService before
 * calling render() since render() is synchronous.
 */
const ClassicTheme: PrintTheme = {
  id: 'classic',
  label: 'classic',

  render(ctx: PrintRenderContext): void {
    const { pdf, t, fontFamily, invoice, party, firm, formatINR, amountInWords, irpQrBase64 } = ctx;

    const safeText = (val: unknown): string => (val == null ? '' : String(val));

    // ─── Header band ────────────────────────────────────────────────────────
    pdf.setFont(fontFamily, 'bold');
    pdf.setFontSize(18);
    pdf.text(invoice?.isBillOfSupply ? t('sales.billOfSupply') : t('sales.taxInvoice'), 105, 18, {
      align: 'center',
    });

    pdf.setFont(fontFamily, 'normal');
    pdf.setFontSize(10);

    // Firm legal name — free text (D-39).
    pdf.setFont(fontFamily, 'bold');
    pdf.text(safeText(firm?.firmName ?? firm?.legalName), 14, 26);
    pdf.setFont(fontFamily, 'normal');
    // 2f: show the seller GSTIN this invoice was issued under (multi-GSTIN firms).
    const sellerGstin = invoice?.sellerGstin || firm?.gstin;
    if (sellerGstin) {
      pdf.text(`${t('tax.gstin')}: ${safeText(sellerGstin)}`, 14, 31);
    }

    // Voucher meta — right column.
    const dateStr = invoice?.voucherDate
      ? new Date(invoice.voucherDate).toISOString().slice(0, 10)
      : '';
    pdf.text(`${t('common.voucherNo')}: ${safeText(invoice?.voucherNumber ?? '')}`, 140, 26);
    pdf.text(`${t('common.date')}: ${dateStr}`, 140, 31);

    // ─── Bill-to block ──────────────────────────────────────────────────────
    pdf.setFont(fontFamily, 'bold');
    pdf.text(t('common.to'), 14, 44);
    pdf.setFont(fontFamily, 'normal');
    pdf.text(safeText(party?.name), 14, 50);
    if (party?.gstin) pdf.text(`${t('tax.gstin')}: ${safeText(party.gstin)}`, 14, 56);
    if (party?.address) pdf.text(safeText(party.address), 14, 62);
    if (invoice?.placeOfSupplyStateCode) {
      pdf.text(`${t('tax.placeOfSupply')}: ${safeText(invoice.placeOfSupplyStateCode)}`, 14, 68);
    }

    // ─── Ship-to / transport block (right column) ───────────────────────────
    // Rendered only when the invoice carries shipping details (VoucherEditor Shipping
    // section -> shipping.* object). Cross-link: SaleInvoice.shipping; keep keys in sync
    // with i18n print.json `shipping` namespace.
    const shipping = invoice?.shipping;
    if (shipping && (shipping.address || shipping.transporter || shipping.vehicleNo)) {
      let sy = 44;
      pdf.setFont(fontFamily, 'bold');
      pdf.text(t('shipping.shipTo'), 120, sy);
      pdf.setFont(fontFamily, 'normal');
      sy += 6;
      if (shipping.address) {
        pdf.text(safeText(shipping.address), 120, sy, { maxWidth: 76 });
        sy += 6;
      }
      if (shipping.transporter) {
        pdf.text(`${t('shipping.transporter')}: ${safeText(shipping.transporter)}`, 120, sy);
        sy += 5;
      }
      if (shipping.vehicleNo) {
        pdf.text(`${t('shipping.vehicle')}: ${safeText(shipping.vehicleNo)}`, 120, sy);
      }
    }

    // invoiceLayout flags: undefined and true both render; only explicit false hides.
    const layout = firm?.invoiceLayout;
    const showHsn = layout?.showHsnColumn !== false;
    const showTerms = layout?.showTermsAndConditions !== false;
    const showSignature = layout?.showSignature !== false;

    // ─── Items table (jspdf-autotable) ──────────────────────────────────────
    const lineItems: any[] = Array.isArray(invoice?.lineItems) ? invoice.lineItems : [];
    const headRow: string[] = ['#', t('common.from')];
    if (showHsn) headRow.push(t('tax.hsn'));
    headRow.push(t('tax.cgst'), t('tax.sgst'), t('tax.igst'), t('common.total'));
    const head = [headRow];
    const body = lineItems.map((line, idx) => {
      const row: string[] = [String(idx + 1), safeText(line?.itemName)];
      if (showHsn) row.push(safeText(line?.hsnSacCode ?? ''));
      row.push(
        formatINR(Number(line?.cgstPaise ?? 0)),
        formatINR(Number(line?.sgstPaise ?? 0)),
        formatINR(Number(line?.igstPaise ?? 0)),
        formatINR(Number(line?.taxableValuePaise ?? 0)),
      );
      return row;
    });

    autoTable(pdf, {
      startY: 78,
      head,
      body,
      theme: 'grid',
      styles: { font: fontFamily, fontSize: 9 },
      headStyles: { font: fontFamily, fontStyle: 'bold' },
      margin: { left: 14, right: 14 },
    });

    const finalY: number = (pdf as any).lastAutoTable?.finalY ?? 90;

    // ─── Totals ─────────────────────────────────────────────────────────────
    pdf.setFont(fontFamily, 'bold');
    pdf.text(
      `${t('common.total')}: ${formatINR(Number(invoice?.totalPaise ?? 0))}`,
      140,
      finalY + 8,
    );

    // Amount in words.
    pdf.setFont(fontFamily, 'normal');
    pdf.text(
      `${t('common.amountInWords')}: ${amountInWords(Number(invoice?.totalPaise ?? 0))}`,
      14,
      finalY + 16,
    );

    // Reverse-charge declaration (mandatory note when tax is payable by the recipient).
    if (invoice?.isReverseCharge) {
      pdf.setFont(fontFamily, 'bold');
      pdf.text(t('tax.reverseCharge'), 14, finalY + 22);
      pdf.setFont(fontFamily, 'normal');
    }

    // Bill of Supply declaration (composition dealer cannot collect tax).
    if (invoice?.isBillOfSupply) {
      pdf.setFont(fontFamily, 'italic');
      pdf.text(t('tax.compositionDeclaration'), 14, finalY + 22);
      pdf.setFont(fontFamily, 'normal');
    }

    // ─── Terms (showTermsAndConditions flag; undefined and true both render) ─
    if (showTerms) {
      pdf.setFont(fontFamily, 'bold');
      pdf.text(t('terms.termsHeader'), 14, finalY + 28);
      pdf.setFont(fontFamily, 'normal');
      pdf.text(t('terms.defaultTerms'), 14, finalY + 34);
    }

    // ─── IRP e-Invoice QR (CGST Rule 48) ────────────────────────────────────
    if (irpQrBase64 && invoice?.eInvoice?.irn) {
      try {
        const irpQrSize = 22; // mm
        pdf.addImage(irpQrBase64, 'PNG', 14, finalY + 38, irpQrSize, irpQrSize);
        pdf.setFont(fontFamily, 'normal');
        pdf.setFontSize(6.5);
        pdf.setTextColor(100, 100, 100);
        pdf.text('e-Invoice QR (CGST Rule 48)', 14, finalY + 38 + irpQrSize + 3, {
          maxWidth: irpQrSize + 10,
        });
        const irnStr = String(invoice.eInvoice.irn);
        pdf.text(`IRN: ${irnStr.slice(0, 20)}...`, 14, finalY + 38 + irpQrSize + 7, {
          maxWidth: 60,
        });
        pdf.setTextColor(0, 0, 0);
      } catch {
        // Non-fatal — continue without QR
      }
    }

    // ─── Signature (showSignature flag; undefined and true both render) ────
    if (showSignature) {
      pdf.text(t('common.signature'), 160, finalY + 50);
    }

    // ─── Footer ─────────────────────────────────────────────────────────────
    pdf.setFontSize(9);
    pdf.text(t('common.thankYou'), 105, 285, { align: 'center' });
  },
};

ThemeRegistry.register(ClassicTheme);

export default ClassicTheme;
