export interface CoaSeed {
  code: string;
  name: string;
  group: string;
  subGroup: string;
  type: 'asset' | 'liability' | 'capital' | 'income' | 'expense';
  isFromTemplate: boolean;
  isSystem: boolean;
}

export const tradingSeeds: CoaSeed[] = [
  {
    code: '1001',
    name: 'Cash',
    group: 'Current Assets',
    subGroup: 'Cash & Bank',
    type: 'asset',
    isFromTemplate: true,
    isSystem: true,
  },
  {
    code: '1002',
    name: 'Bank',
    group: 'Current Assets',
    subGroup: 'Cash & Bank',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '1003',
    name: 'Sundry Debtors',
    group: 'Current Assets',
    subGroup: 'Receivables',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '1004',
    name: 'Stock',
    group: 'Current Assets',
    subGroup: 'Inventory',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '1005',
    name: 'Advance to Suppliers',
    group: 'Current Assets',
    subGroup: 'Advances',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '1006',
    name: 'Security Deposits',
    group: 'Current Assets',
    subGroup: 'Advances',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '1007',
    name: 'TDS Receivable',
    group: 'Current Assets',
    subGroup: 'Tax Assets',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '1008',
    name: 'Prepaid Expenses',
    group: 'Current Assets',
    subGroup: 'Other Assets',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '1100',
    name: 'IGST Input Credit',
    group: 'GST ITC',
    subGroup: 'Input Tax Credit',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '1101',
    name: 'CGST Input Credit',
    group: 'GST ITC',
    subGroup: 'Input Tax Credit',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '1102',
    name: 'SGST Input Credit',
    group: 'GST ITC',
    subGroup: 'Input Tax Credit',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '1501',
    name: 'Plant & Machinery',
    group: 'Fixed Assets',
    subGroup: 'Tangible Assets',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '1502',
    name: 'Furniture',
    group: 'Fixed Assets',
    subGroup: 'Tangible Assets',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '1503',
    name: 'Computers',
    group: 'Fixed Assets',
    subGroup: 'Tangible Assets',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '1504',
    name: 'Vehicles',
    group: 'Fixed Assets',
    subGroup: 'Tangible Assets',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '1510',
    name: 'Less: Accumulated Depreciation',
    group: 'Fixed Assets',
    subGroup: 'Contra Assets',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '2001',
    name: 'Sundry Creditors',
    group: 'Current Liabilities',
    subGroup: 'Payables',
    type: 'liability',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '2002',
    name: 'Advance from Customers',
    group: 'Current Liabilities',
    subGroup: 'Advances',
    type: 'liability',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '2003',
    name: 'TDS Payable',
    group: 'Current Liabilities',
    subGroup: 'Tax Liabilities',
    type: 'liability',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '2004',
    name: 'TCS Payable',
    group: 'Current Liabilities',
    subGroup: 'Tax Liabilities',
    type: 'liability',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '2005',
    name: 'GST Payable',
    group: 'GST',
    subGroup: 'GST Liabilities',
    type: 'liability',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '2006',
    name: 'IGST Payable',
    group: 'GST',
    subGroup: 'GST Liabilities',
    type: 'liability',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '2007',
    name: 'CGST Payable',
    group: 'GST',
    subGroup: 'GST Liabilities',
    type: 'liability',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '2008',
    name: 'SGST Payable',
    group: 'GST',
    subGroup: 'GST Liabilities',
    type: 'liability',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '2009',
    name: 'MSME Interest Payable',
    group: 'Current Liabilities',
    subGroup: 'Other Liabilities',
    type: 'liability',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '2010',
    name: 'Salary Payable',
    group: 'Current Liabilities',
    subGroup: 'Payroll',
    type: 'liability',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '3001',
    name: 'Capital Account',
    group: 'Capital',
    subGroup: "Owner's Equity",
    type: 'capital',
    isFromTemplate: true,
    isSystem: true,
  },
  {
    code: '3002',
    name: 'Drawings',
    group: 'Capital',
    subGroup: "Owner's Equity",
    type: 'capital',
    isFromTemplate: true,
    isSystem: true,
  },
  {
    code: '3003',
    name: 'Retained Earnings',
    group: 'Capital',
    subGroup: "Owner's Equity",
    type: 'capital',
    isFromTemplate: true,
    isSystem: true,
  },
  {
    code: '4001',
    name: 'Sales - Trading',
    group: 'Income',
    subGroup: 'Trading Income',
    type: 'income',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '4002',
    name: 'Other Income',
    group: 'Income',
    subGroup: 'Other',
    type: 'income',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '4003',
    name: 'Interest Income',
    group: 'Income',
    subGroup: 'Other',
    type: 'income',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '4004',
    name: 'Commission Received',
    group: 'Income',
    subGroup: 'Other',
    type: 'income',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '4005',
    name: 'Round-Off Gain',
    group: 'Income',
    subGroup: 'Other',
    type: 'income',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    // #14: contra-revenue. Credit notes (sales returns) debit this instead of netting straight into
    // 4001 Sales, so the P&L can show gross Sales less Sales Returns = net sales.
    code: '4009',
    name: 'Sales Returns',
    group: 'Income',
    subGroup: 'Trading Income',
    type: 'income',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5001',
    name: 'Purchases',
    group: 'Expenses',
    subGroup: 'Direct Expenses',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5002',
    name: 'Freight Inward',
    group: 'Expenses',
    subGroup: 'Direct Expenses',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5003',
    name: 'Salary Expense',
    group: 'Expenses',
    subGroup: 'Indirect Expenses',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5004',
    name: 'Rent',
    group: 'Expenses',
    subGroup: 'Indirect Expenses',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5005',
    name: 'Electricity',
    group: 'Expenses',
    subGroup: 'Indirect Expenses',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5006',
    name: 'Commission Payable',
    group: 'Expenses',
    subGroup: 'Indirect Expenses',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5007',
    name: 'Professional Fees',
    group: 'Expenses',
    subGroup: 'Indirect Expenses',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5008',
    name: 'Bank Charges',
    group: 'Expenses',
    subGroup: 'Indirect Expenses',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5009',
    name: 'Depreciation',
    group: 'Expenses',
    subGroup: 'Indirect Expenses',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5010',
    name: 'Round-Off Loss',
    group: 'Expenses',
    subGroup: 'Other',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5011',
    name: 'Misc Expense',
    group: 'Expenses',
    subGroup: 'Other',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
];

// Standard ledgers the posting engine + statutory flows reference but that were
// missing from the original trading template, so a freshly seeded firm could hit
// "account code not found" when posting capital-goods ITC, section-wise TDS,
// asset disposal, or loan interest. Layered onto EVERY business type now; existing
// firms are backfilled by InventoryMigrationService. Codes here MUST stay in sync
// with the CODE_* constants in sales/ledger-posting/ledger-posting.service.ts.
// (Cess 1012/2018 + Wastage 5018 are intentionally omitted: 1012 collides with
// manufacturing's "Finished Goods" and all three are already backfilled by the
// existing inventory migration.)
export const commonComplianceSeeds: CoaSeed[] = [
  {
    code: '1103',
    name: 'Capital Goods ITC Deferred',
    group: 'GST ITC',
    subGroup: 'Input Tax Credit',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  // Salary Advance — debit account for payroll advance payments (the salary→ledger
  // bridge posts Dr 1014 / Cr cash). Originally code 1013, but that collided with
  // service-firm "Work In Progress - Services"; re-coded to the free 1014 and added
  // here so EVERY business type gets it at firm creation. Existing firms are
  // backfilled by migration 0038_finance_backfill_salary_advance_coa. MUST stay in
  // sync with CODE_SALARY_ADVANCE in salary/salary-ledger-posting.service.ts.
  {
    code: '1014',
    name: 'Salary Advance',
    group: 'Current Assets',
    subGroup: 'Loans & Advances',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '2011',
    name: 'TDS Payable - 194C (Contractors)',
    group: 'Current Liabilities',
    subGroup: 'Tax Liabilities',
    type: 'liability',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '2012',
    name: 'TDS Payable - 194H (Commission)',
    group: 'Current Liabilities',
    subGroup: 'Tax Liabilities',
    type: 'liability',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '2013',
    name: 'TDS Payable - 194J (Professional)',
    group: 'Current Liabilities',
    subGroup: 'Tax Liabilities',
    type: 'liability',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '2014',
    name: 'TDS Payable - 194Q (Purchases)',
    group: 'Current Liabilities',
    subGroup: 'Tax Liabilities',
    type: 'liability',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '4007',
    name: 'Gain on Disposal of Fixed Assets',
    group: 'Income',
    subGroup: 'Other',
    type: 'income',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5013',
    name: 'Loss on Disposal of Fixed Assets',
    group: 'Expenses',
    subGroup: 'Other',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5015',
    name: 'Interest on Loan / OD',
    group: 'Expenses',
    subGroup: 'Finance Charges',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  // Contra for per-account opening balances (OpeningBalanceService posts the
  // account line against this so the opening books net to zero). System: not
  // user-deletable. Note 3100 is taken by Retained Earnings (fy-close).
  {
    code: '3004',
    name: 'Opening Balance Equity',
    group: 'Capital',
    subGroup: "Owner's Equity",
    type: 'capital',
    isFromTemplate: true,
    isSystem: true,
  },
];

// Surat/Gujarat textile-trade ledgers layered on top of the trading template:
// fabric stock stages, job-work income/charges split by process (so dyeing 5%/18%
// and printing post to distinct ledgers — plan D13/§4), brokerage (dalali),
// commercial discount (kasar-vatav), and interest (vyaj). Used by the 'textile'
// business type and backfilled to existing textile firms by InventoryMigrationService.
export const textileDelta: CoaSeed[] = [
  {
    code: '1020',
    name: 'Grey Fabric Stock',
    group: 'Current Assets',
    subGroup: 'Inventory',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '1021',
    name: 'Finished Fabric Stock',
    group: 'Current Assets',
    subGroup: 'Inventory',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '1022',
    name: 'Stock at Job Worker',
    group: 'Current Assets',
    subGroup: 'Inventory',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '4021',
    name: 'Job Work Income - Dyeing',
    group: 'Income',
    subGroup: 'Service Income',
    type: 'income',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '4022',
    name: 'Job Work Income - Printing',
    group: 'Income',
    subGroup: 'Service Income',
    type: 'income',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '4023',
    name: 'Job Work Income - Embroidery',
    group: 'Income',
    subGroup: 'Service Income',
    type: 'income',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '4024',
    name: 'Job Work Income - Other',
    group: 'Income',
    subGroup: 'Service Income',
    type: 'income',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '4025',
    name: 'Dalali (Brokerage) Received',
    group: 'Income',
    subGroup: 'Other',
    type: 'income',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '4026',
    name: 'Vyaj (Interest) Received',
    group: 'Income',
    subGroup: 'Other',
    type: 'income',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '4027',
    name: 'Kasar-Vatav Received',
    group: 'Income',
    subGroup: 'Other',
    type: 'income',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5020',
    name: 'Freight Outward',
    group: 'Expenses',
    subGroup: 'Direct Expenses',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5021',
    name: 'Job Work Charges - Dyeing',
    group: 'Expenses',
    subGroup: 'Direct Expenses',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5022',
    name: 'Job Work Charges - Printing',
    group: 'Expenses',
    subGroup: 'Direct Expenses',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5023',
    name: 'Job Work Charges - Embroidery',
    group: 'Expenses',
    subGroup: 'Direct Expenses',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5024',
    name: 'Job Work Charges - Other',
    group: 'Expenses',
    subGroup: 'Direct Expenses',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5025',
    name: 'Dalali (Brokerage) Paid',
    group: 'Expenses',
    subGroup: 'Indirect Expenses',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5026',
    name: 'Kasar-Vatav Allowed',
    group: 'Expenses',
    subGroup: 'Direct Expenses',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
];

// Trading template = base trading ledgers + standard compliance ledgers. All other
// templates spread this so they inherit the compliance set too.
export const tradingTemplate: CoaSeed[] = [...tradingSeeds, ...commonComplianceSeeds];

export const manufacturingSeeds: CoaSeed[] = [
  ...tradingTemplate,
  {
    code: '1010',
    name: 'Raw Material',
    group: 'Current Assets',
    subGroup: 'Inventory',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '1011',
    name: 'Work In Progress',
    group: 'Current Assets',
    subGroup: 'Inventory',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '1012',
    name: 'Finished Goods',
    group: 'Current Assets',
    subGroup: 'Inventory',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5050',
    name: 'Manufacturing Expenses',
    group: 'Manufacturing',
    subGroup: 'Production Costs',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5051',
    name: 'Power & Fuel',
    group: 'Manufacturing',
    subGroup: 'Production Costs',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5052',
    name: 'Consumables',
    group: 'Manufacturing',
    subGroup: 'Production Costs',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5053',
    name: 'Job Work Charges',
    group: 'Manufacturing',
    subGroup: 'Production Costs',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5060',
    name: 'Manufacturing Cost Variance',
    group: 'Manufacturing',
    subGroup: 'Production Costs',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '4020',
    name: 'Job-Work Service Income',
    group: 'Income',
    subGroup: 'Service Income',
    type: 'income',
    isFromTemplate: true,
    isSystem: false,
  },
];

export const serviceSeeds: CoaSeed[] = [
  ...tradingTemplate.filter((a) => a.code !== '1004'),
  {
    code: '1013',
    name: 'Work In Progress - Services',
    group: 'Current Assets',
    subGroup: 'Inventory',
    type: 'asset',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '4010',
    name: 'Service Revenue',
    group: 'Income',
    subGroup: 'Service Income',
    type: 'income',
    isFromTemplate: true,
    isSystem: false,
  },
  {
    code: '5060',
    name: 'Professional Charges',
    group: 'Expenses',
    subGroup: 'Direct Expenses',
    type: 'expense',
    isFromTemplate: true,
    isSystem: false,
  },
];

export const compositionSeeds: CoaSeed[] = [
  // Composition dealers cannot claim input tax credit — drop every ITC ledger
  // (1100/1101/1102 regular + 1103 capital-goods deferred).
  ...tradingTemplate.filter((a) => !['1100', '1101', '1102', '1103'].includes(a.code)),
  {
    code: '2020',
    name: 'Composition Tax Payable',
    group: 'GST',
    subGroup: 'GST Liabilities',
    type: 'liability',
    isFromTemplate: true,
    isSystem: false,
  },
];

// Surat/Gujarat textile trade + processing preset.
export const textileSeeds: CoaSeed[] = [...tradingTemplate, ...textileDelta];

export const COA_SEED_MAP: Record<string, CoaSeed[]> = {
  trading: tradingTemplate,
  manufacturing: manufacturingSeeds,
  service: serviceSeeds,
  composition: compositionSeeds,
  textile: textileSeeds,
};
